export enum AlertStatus {
  PENDING = "PENDING", // Default status
  FALSE_ALERT = "FALSE_ALERT", // [ST.FA]
  IMPROVED = "IMPROVED", // [ST.IM]
  WORSENED = "WORSENED", // [ST.WO]
  CONTAINED = "CONTAINED", // [CONF.CL]
  EXAMINATION_CONTINUES = "EXAMINATION_CONTINUES", // [CONF.AI]
  CASES_DECREASED = "CASES_DECREASED", // [CMT.CD]
  NO_CHANGE = "NO_CHANGE", // [CMT.NCH]
  CASES_INCREASED = "CASES_INCREASED", // [CMT.CI]
  DEATHS_OCCURRED = "DEATHS_OCCURRED", // [CMT.DO]
}
